services:

  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_user -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-orders:
    image: postgres:16-alpine
    container_name: postgres-orders
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orders_user -d orders_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-inventory:
    image: postgres:16-alpine
    container_name: postgres-inventory
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: ${INVENTORY_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_inventory_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U inventory_user -d inventory_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-payment:
    image: postgres:16-alpine
    container_name: postgres-payment
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U payment_user -d payment_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-notification:
    image: postgres:16-alpine
    container_name: postgres-notification
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U notification_user -d notification_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_auth_data:
  postgres_orders_data:
  postgres_inventory_data:
  postgres_payment_data:
  postgres_notification_data:
  redis_data:
